### ISSUE TITLE
Update Note at Existing Timestamp

### ISSUE THREAD

**Issue by bennett-zhang** [cse110-fq22-group40/cse110-fq22-group40#106]
# Update Note at Existing Timestamp

When the user tries submitting a note at an existing timestamp, a popup appears asking if the user would like to update that note.

The "No" option works well. The "Yes" option just reloads the page.

## What?
What might be causing our problem

- We just haven't implemented the functionality yet.

## Where?
Where might the problem be

- audio-object.js line 165

## How?
How might we fix the problem

- Replace the TODO in audio-object.js on lines 164 & 165 with actual code.

**Comment by ryan-truong** [comment]
Hi Bennett,

On the current implementation of the `staging` branch it seems like the note is updating for me after the page reloads. I have attached a video of the note updating. Let me know if there are other issues or additional work this feature needs!


https://user-images.githubusercontent.com/75468904/204118957-1844e3d1-7dfe-4cef-b232-40e8c7ad5df6.mov

**Comment by hongyuejin** [comment]
The code has been implemented but the documentation hasn't been updated. 
Now the documentation has been fixed.
