### ISSUE TITLE
Empty TypeA Folder Not Showing Up Bug

### ISSUE THREAD

**Issue by ernestl123** [cse110-fq22-group40/cse110-fq22-group40#72]
# Main Problem
Creating an empty TypeA folder in a TypeF page, exiting that page and re-entering that page will not visually show the empty TypeA folder.

## What?
Somewhere in front end code it is not displaying existing empty TypeA folders

## Where?
Potentially TypeA.html or backend code

## How?
Check localstorage to see if empty typeA objects exist after creation. If so, it's front end problem. Otherwise, it's backend issue.

**Comment by ernestl123** [comment]
Update: The bug only occurs when you create an empty **Type A** folder inside a **Type F** folder which already has a **Type A** folder with an audio object and notes.

Ex. "Type F" -> "Type A1" -> "AudioObject 1" -> "Notes" and then you try to add an empty TypeA folder inside "Type F"

**Comment by billysud** [comment]
fixed during our meeting
