### ISSUE TITLE
Change Home Screen ~Vibe~

### ISSUE THREAD

**Issue by SailorForSchool** [cse110-fq22-group40/cse110-fq22-group40#80]
# Visual Distinction Between Folders

## What?
The user should be able to tell what folder type they are in based on the UI, am I looking at audio files? or am I looking and folders?

## Where?
On the front page of the app and adjustments to each folder to make them feel unique and connected

## How?
Perhaps the workspaces can be labeled as the home page and each workspace can take up more room with an uploaded background? Maybe that is too many features at once.

**Comment by Emmanuel-Serrano** [comment]
The application now holds where you are at on the top left of the screen
